name: Build and Deploy Hugo Site

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true  # For SCSS/SASS support

      - name: Install Pandoc
        run: sudo apt-get install -y pandoc

      - name: Convert Org files to Markdown
        run: |
          find content -name "*.org" -type f | while read file; do
            output_file="${file%.org}.md"
            echo "Converting $file to $output_file"
            pandoc "$file" -f org -t markdown -o "$output_file"
          done

      - name: Build site
        run: hugo --minify

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages  # The branch the site will be deployed to
